name = "Create Astral"
author = "Laskyyy"
version = "v2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebd7398a7dad0d2111e925b7831a937e0afde1f46eb4be776529a523462acd47"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
