name = "Create Astral"
author = "Laskyyy"
version = "v2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a982a8b098c65d74293cee3aa59d6925154e16b169e1fdb60748202f6d1bae5"

[versions]
fabric = "0.14.12"
minecraft = "1.18.2"
