name = "Create Astral"
author = "Laskyyy"
version = "v2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e65b9864b2bbbb17e462fe9029ac2b6546bfd7096b50504e4cad4c91c380079"

[versions]
fabric = "0.14.12"
minecraft = "1.18.2"
