name = "Create Astral"
author = "Laskyyy"
version = "v2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ba8d196f2e94796d8305455b569fef39f05a48cbd1a123581a1b0932b8d0ec2"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
